name: Greeting on variable day

on:
  push

env:
  DAY_OF_WEEK: Monday
  REDIS_URL: ${{ secrets.REDIS_URL }}

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK! , $REDIS_URL, $REDIS"
        env:
          First_Name: Mona